name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - main
jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - run: go test *.go
      - run: go run math.go